version: "3.8"

services:
  server:
    build:
      context: .
      target: development
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    environment:
      SERVER_PORT: "3000"
      TIMEZONE: UTC
      JOB_STORE_SOURCE: mysql
      JOB_STORE_URL: mysql://root:password@mysql:3306/test
      DEBUG: cronyx:*
    command: bun run dev
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test

volumes:
  node-modules: {}
