apiVersion: v1
kind: Service
metadata:
  labels:
    service: cronyx-server
  name: cronyx-server
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 3000
      targetPort: 3000
  selector:
    service: cronyx-server
status:
  loadBalancer: {}
